[pytest]
addopts= -vs
        --alluredir=./reports/allure-results
        --clean-alluredir

testpaths = ./testcase/Process/
python_files = test_*.py
python_classes = Test*
python_functions = test_*
markers =                 #配合 -m 参数使用 例如 pytest -m slow
    slow: 慢速测试
    api: 接口测试
    unit: 单元测试

;查看allure报告在终端
;pytest
;allure serve reports/allure-results